### ISSUE TITLE
Signup 테스트에 관한 공유입니다

### ISSUE THREAD

**Issue by jungds00** [Jin-hyeok2/Carrot_auction#17]
제가 따로 해본 Signup 관련 테스트 진행중에서 발생한 오류 공유드립니다!

![1](https://user-images.githubusercontent.com/84696143/220007615-46c81ba1-66de-452f-bf88-1e774dddea73.PNG)
![2](https://user-images.githubusercontent.com/84696143/220007620-d04bc838-966b-4df5-9a44-3e92db51e547.PNG)

위와 같은 오류가 발견되어서 생성자 관련 오류인것같아 SignUp부분에  @NoArgsConstructor, @AllArgsConstructor를 추가했을땐    제대로 작동한것을 확인할 수 있었습니다. 혹시 테스트 과정에서 제가 설정한 부분이랑 다르시면 관련부분 캡쳐 부탁드리겠습니다!
![3](https://user-images.githubusercontent.com/84696143/220007623-c544be08-7ecf-4000-a306-c6f50bf33fc3.PNG)
![4](https://user-images.githubusercontent.com/84696143/220007624-828e9d3b-5cb2-4c6a-98ed-d613e6cfb4b6.PNG)

**Comment by Jin-hyeok2** [comment]
![image](https://user-images.githubusercontent.com/91868151/220015367-026cfa9f-fa6a-4ed3-a1de-649545fa8d0f.png)
이 부분에서 Buil and run using 부분이 Intellij IDEA 가 아닌 Gradle로 설정했을 땐 해당 설정 없이 잘 돌아 가는 것 같아요
위 설정 때문에 서버 구동 중지 시에 에러로 표현됐던 거구요
제가 해당 부분 Intellij IDEA로 설정 바꾸니 같은 현상이 일어났습니다.
해당 부분 수정하여 메인에 머지하도록 하겠습니다 :)
